# Generated by Django 3.2.8 on 2021-12-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_alter_comentario_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcertamen',
            name='id_preguntas',
            field=models.CharField(max_length=300),
        ),
    ]
